export default {
  "admin": [
    {
        "breadcrumbName":"index",
        "icon":"BankOutlined",
        "path":"/index"
    },
    {
        "breadcrumbName":"doc",
        "icon":"FileTextOutlined",
        "path":"/doc"
    },
    {
        "breadcrumbName":"guide",
        "icon":"SendOutlined",
        "path":"/guide"
    },
    {
        "breadcrumbName":"permission",
        "icon":"PropertySafetyOutlined",
        "path":"/authority",
        "children":[
            {
                "breadcrumbName":"pagePermission",
                "path":"/pageAuthority"
            },
            {
                "breadcrumbName":"rolePermission",
                "path": "/characterAuthority"
            }
        ]
    },
    {
        "breadcrumbName":"icon",
        "icon":"ItalicOutlined",
        "path":"/iconShow"
    },
    {
        "breadcrumbName":"component",
        "icon":"AppstoreAddOutlined",
        "path":"/component",
        "children":[
          {
              "breadcrumbName":"richText",
              "path":"/richText"
          },
          {
              "breadcrumbName":"json",
              "path":"/json"
          },
          {
              "breadcrumbName":"markDown",
              "path":"/markDown"
          },
          {
              "breadcrumbName":"dropZone",
              "path":"/dropZone"
          },
          {
              "breadcrumbName":"headUpload",
              "path":"/headUpload"
          },
          {
              "breadcrumbName":"stiky",
              "path":"/stiky"
          },
      ]
    },
    {
        "breadcrumbName":"chart",
        "icon":"AreaChartOutlined",
        "path":"/chart"
    },
    {
        "breadcrumbName": "routeTitle",
        "path":"/child",
        "icon":"ProjectOutlined",
        "children":[
            {
                "breadcrumbName":"route1",
                "path":"/routerTest1",
                "children": [
                    {
                        "breadcrumbName":"route11",
                        "path":"/routerTest11"
                    },
                    {
                        "breadcrumbName":"route12",
                        "path":"/routerTest12",
                        "children": [
                            {
                                "breadcrumbName":"route121",
                                "path":"/routerTest121"
                                
                            },
                            {
                                "breadcrumbName":"route122",
                                "path":"/routerTest122"
                            }
                        ]
                    },
                    {
                        "breadcrumbName":"route13",
                        "path":"/routerTest13"
                    }
                ]
            },
            {
                "breadcrumbName":"route2",
                "path":"/routerTest2"
            }
        ]
    },
    {
        "breadcrumbName":"table",
        "icon":"TableOutlined",
        "path":"/table"
    },
  ],
  "editor": [
    {
        "breadcrumbName":"index",
        "icon":"BankOutlined",
        "path":"/index"
    },
    {
        "breadcrumbName":"doc",
        "icon":"FileTextOutlined",
        "path":"/doc"
    },
    {
        "breadcrumbName":"guide",
        "icon":"SendOutlined",
        "path":"/guide"
    },
    {
        "breadcrumbName":"permission",
        "icon":"PropertySafetyOutlined",
        "path":"/authority",
        "children":[
          {
              "breadcrumbName":"pagePermission",
              "path":"/pageAuthority"
          }
      ]
    },
    {
        "breadcrumbName": "routeTitle",
        "path":"/child",
        "children":[
            {
                "breadcrumbName":"route1",
                "path":"/routerTest1",
                "children": [
                    {
                        "breadcrumbName":"route11",
                        "path":"/routerTest11"
                    },
                    {
                        "breadcrumbName":"route12",
                        "path":"/routerTest12",
                        "children": [
                            {
                                "breadcrumbName":"route121",
                                "path":"/routerTest121"
                            },
                            {
                                "breadcrumbName":"route122",
                                "path":"/routerTest122"
                            }
                        ]
                    },
                    {
                        "breadcrumbName":"route13",
                        "path":"/routerTest13"
                    }
                ]
            },
            {
                "breadcrumbName":"route2",
                "path":"/routerTest2"
            }
        ]
    },
    {
        "breadcrumbName":"icon",
        "icon":"SendOutlined",
        "path":"/iconShow"
    },
    {
        "breadcrumbName":"component",
        "icon":"PropertySafetyOutlined",
        "path":"/component",
        "children":[
          {
              "breadcrumbName":"richText",
              "path":"/richText"
          },
          {
              "breadcrumbName":"json",
              "path":"/json"
          },
          {
              "breadcrumbName":"markDown",
              "path":"/markDown"
          },
          {
              "breadcrumbName":"dropZone",
              "path":"/dropZone"
          },
          {
              "breadcrumbName":"headUpload",
              "path":"/headUpload"
          },
          {
              "breadcrumbName":"stiky",
              "path":"/stiky"
          },
      ]
    },
  ],
  "visitor": [
    {
        "breadcrumbName":"index",
        "icon":"BankOutlined",
        "path":"/index"
    },
    {
        "breadcrumbName":"doc",
        "icon":"FileTextOutlined",
        "path":"/doc"
    },
    {
        "breadcrumbName":"guide",
        "icon":"SendOutlined",
        "path":"/guide"
    },
  ]


}