export default {
  "admin": [
    {
        "breadcrumbName":"index",
        "icon":"BankOutlined",
        "path":"/index"
    },
    {
        "breadcrumbName":"doc",
        "icon":"FileTextOutlined",
        "path":"/doc"
    },
    {
        "breadcrumbName":"guide",
        "icon":"SendOutlined",
        "path":"/guide"
    },
    {
        "breadcrumbName":"permission",
        "icon":"PropertySafetyOutlined",
        "path":"/authority",
        "children":[
            {
                "breadcrumbName":"pagePermission",
                "path":"/pageAuthority"
            },
            {
                "breadcrumbName":"rolePermission",
                "path":"/characterAuthority",
                "icon":"SendOutlined"
            }
        ]
    },
    {
        "breadcrumbName": "routeTitle",
        "path":"/child",
        "children":[
            {
                "breadcrumbName":"route1",
                "path":"/routerTest1",
                "icon":"SendOutlined",
                "children": [
                    {
                        "breadcrumbName":"route11",
                        "path":"/routerTest11",
                        "icon":"SendOutlined"
                    },
                    {
                        "breadcrumbName":"route12",
                        "path":"/routerTest12",
                        "icon":"SendOutlined",
                        "children": [
                            {
                                "breadcrumbName":"route121",
                                "path":"/routerTest121",
                                "icon":"SendOutlined"
                                
                            },
                            {
                                "breadcrumbName":"route122",
                                "path":"/routerTest122",
                                "icon":"SendOutlined"
                            }
                        ]
                    },
                    {
                        "breadcrumbName":"route13",
                        "path":"/routerTest13",
                        "icon":"SendOutlined"
                    }
                ]
            },
            {
                "breadcrumbName":"route2",
                "path":"/routerTest2",
                "icon":"SendOutlined"
            }
        ]
    }
  ],
  "editor": [
    {
        "breadcrumbName":"index",
        "icon":"BankOutlined",
        "path":"/index"
    },
    {
        "breadcrumbName":"doc",
        "icon":"FileTextOutlined",
        "path":"/doc"
    },
    {
        "breadcrumbName":"guide",
        "icon":"SendOutlined",
        "path":"/guide"
    },
    {
        "breadcrumbName":"permission",
        "icon":"PropertySafetyOutlined",
        "path":"/authority",
        "children":[
          {
              "breadcrumbName":"pagePermission",
              "path":"/pageAuthority"
          }
      ]
    },
    {
        "breadcrumbName": "routeTitle",
        "path":"/child",
        "children":[
            {
                "breadcrumbName":"route1",
                "path":"/routerTest1",
                "icon":"SendOutlined",
                "children": [
                    {
                        "breadcrumbName":"route11",
                        "path":"/routerTest11",
                        "icon":"SendOutlined"
                    },
                    {
                        "breadcrumbName":"route12",
                        "path":"/routerTest12",
                        "icon":"SendOutlined",
                        "children": [
                            {
                                "breadcrumbName":"route121",
                                "path":"/routerTest121",
                                "icon":"SendOutlined"
                                
                            },
                            {
                                "breadcrumbName":"route122",
                                "path":"/routerTest122",
                                "icon":"SendOutlined"
                            }
                        ]
                    },
                    {
                        "breadcrumbName":"route13",
                        "path":"/routerTest13",
                        "icon":"SendOutlined"
                    }
                ]
            },
            {
                "breadcrumbName":"route2",
                "path":"/routerTest2",
                "icon":"SendOutlined"
            }
        ]
    }
  ],
  "visitor": [
    {
        "breadcrumbName":"index",
        "icon":"BankOutlined",
        "path":"/index"
    },
    {
        "breadcrumbName":"doc",
        "icon":"FileTextOutlined",
        "path":"/doc"
    },
    {
        "breadcrumbName":"guide",
        "icon":"SendOutlined",
        "path":"/guide"
    },
  ]


}